### ISSUE TITLE
pptx.exc.PackageNotFoundError: Package not found at '../Lecture03bECD.pptx'

### ISSUE THREAD

**Issue by ralmond** [ssine/pptx2md#1]
I'm trying to convert a back catalog of powerpoint lectures to md.  The first two I did worked great.  The next two, I'm getting a mysterious error:

```
pptx2md ../Lecture03bECD.pptx -o Lecture03bECD.md
/Users/ralmond/Library/Python/3.7/lib/python/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "/Users/ralmond/bin/pptx2md", line 8, in <module>
    sys.exit(main())
  File "/Users/ralmond/Library/Python/3.7/lib/python/site-packages/pptx2md/__main__.py", line 77, in main
    prs = Presentation(file_path)
  File "/Users/ralmond/Library/Python/3.7/lib/python/site-packages/pptx/api.py", line 28, in Presentation
    presentation_part = Package.open(pptx).main_document_part
  File "/Users/ralmond/Library/Python/3.7/lib/python/site-packages/pptx/opc/package.py", line 125, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "/Users/ralmond/Library/Python/3.7/lib/python/site-packages/pptx/opc/pkgreader.py", line 33, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "/Users/ralmond/Library/Python/3.7/lib/python/site-packages/pptx/opc/phys_pkg.py", line 32, in __new__
    raise PackageNotFoundError("Package not found at '%s'" % pkg_file)
pptx.exc.PackageNotFoundError: Package not found at '../Lecture03bECD.pptx'
dhcp138177:Markdown ralmond$ 
```

I just figured this out.  PPT saved the file to the wrong directory, so the file did not exist.  I'll leave this as a minor issue, because "Package not found" is a confusing error message.

**Comment by ssine** [comment]
The error is counter intuitive, so I added file existence check before loading, thanks!

**Comment by yulman19** [comment]
i'm having this error on some of the files I try to convert, any reason why?

**Comment by ssine** [comment]
> i'm having this error on some of the files I try to convert, any reason why?

If this error happens on well-formed pptx file, please send them to `liu.siyao@qq.com` for debugging.
