### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by vonschutter** [ssine/pptx2md#18]
Command: pptx2md -o redme.md -i images infile.pptx

Output: 
processing slide 1...
Traceback (most recent call last):
  File "/home/tangarora/.local/bin/pptx2md", line 8, in <module>
    sys.exit(main())
  File "/home/tangarora/.local/lib/python3.9/site-packages/pptx2md/__main__.py", line 117, in main
    parse(prs, out)
  File "/home/tangarora/.local/lib/python3.9/site-packages/pptx2md/parser.py", line 176, in parse
    process_picture(shape)
  File "/home/tangarora/.local/lib/python3.9/site-packages/pptx2md/parser.py", line 130, in process_picture
    common_path = os.path.commonpath([g.out_path, g.img_path])
  File "/usr/lib/python3.9/posixpath.py", line 510, in commonpath
    raise ValueError("Can't mix absolute and relative paths") from None
ValueError: Can't mix absolute and relative paths

**Comment by vonschutter** [comment]
no potions work

**Comment by vonschutter** [comment]
Options sorry

**Comment by ssine** [comment]
Bug fixed, upgrade with `pip install --upgrade pptx2md==0.7.9` and try again.
