### ISSUE TITLE
M1 Mac is unable to run command

### ISSUE THREAD

**Issue by PiSaucer** [ssine/pptx2md#21]
When I tried to run ```pptx2md [filename]``` I get a bunch of errors. This is what I am left with:

```zsh
Traceback (most recent call last):
  File "/opt/homebrew/bin/pptx2md", line 5, in <module>
    from pptx2md.__main__ import main
  File "/opt/homebrew/lib/python3.9/site-packages/pptx2md/__main__.py", line 1, in <module>
    from pptx import Presentation
  File "/opt/homebrew/lib/python3.9/site-packages/pptx/__init__.py", line 14, in <module>
    from pptx.api import Presentation  # noqa
  File "/opt/homebrew/lib/python3.9/site-packages/pptx/api.py", line 15, in <module>
    from .package import Package
  File "/opt/homebrew/lib/python3.9/site-packages/pptx/package.py", line 6, in <module>
    from pptx.opc.package import OpcPackage
  File "/opt/homebrew/lib/python3.9/site-packages/pptx/opc/package.py", line 13, in <module>
    from pptx.opc.oxml import CT_Relationships, serialize_part_xml
  File "/opt/homebrew/lib/python3.9/site-packages/pptx/opc/oxml.py", line 5, in <module>
    from lxml import etree
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/lxml/etree.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/opt/homebrew/lib/python3.9/site-packages/lxml/etree.cpython-39-darwin.so: mach-o, but wrong architecture
	/opt/homebrew/lib/python3.9/site-packages/lxml/etree.cpython-39-darwin.so: mach-o, but wrong architecture
```

**Comment by ssine** [comment]
Dependent package https://github.com/lxml/lxml (which is used by python-pptx to parse pptx files) doesn't have a mac m1 build. There is nothing I can do right now. When lxml provides a m1 build (and used by python-pptx) I will upgrade to that python-pptx version.

Maybe you can try VM or Docker, Good luck.

**Comment by PiSaucer** [comment]
I was able to get hold of a Windows 11 machine for my project. Thank you for your time and energy in helping resolve this issue.
