### ISSUE TITLE
NameError: name 'width' is not defined when the exported image is wmf format.

### ISSUE THREAD

**Issue by kxxt** [ssine/pptx2md#23]
Error: 
```output
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pptx2md\__main__.py", line 123, in <module>
    main()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pptx2md\__main__.py", line 119, in main
    parse(prs, out)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pptx2md\parser.py", line 175, in parse
    process_picture(shape)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pptx2md\parser.py", line 137, in process_picture
    out.put_image(os.path.splitext(img_outputter_path)[0]+'.png', width)
NameError: name 'width' is not defined
```
https://github.com/ssine/pptx2md/blob/6d904dc9b6828574a3adfe29b2228aa1158bf187/pptx2md/parser.py#L118-L139

 `width`  is undefined.

I can open a pull request to fix this.

**Comment by ssine** [comment]
version 1.0.1 published for this fix
