### ISSUE TITLE
Error on Windows: module 'collections' has no attribute 'abc'

### ISSUE THREAD

**Issue by h3xstream** [ssine/pptx2md#31]
Error when launching pptx2md: 

`AttributeError: module 'collections' has no attribute 'abc'`

```
Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\pptx\compat\__init__.py", line 10, in <module>
    Container = collections.abc.Container
AttributeError: module 'collections' has no attribute 'abc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python310\Scripts\pptx2md.exe\__main__.py", line 4, in <module>
  File "C:\Python\Python310\lib\site-packages\pptx2md\__main__.py", line 1, in <module>
    from pptx import Presentation
  File "C:\Python\Python310\lib\site-packages\pptx\__init__.py", line 14, in <module>
    from pptx.api import Presentation  # noqa
  File "C:\Python\Python310\lib\site-packages\pptx\api.py", line 15, in <module>
    from .package import Package
  File "C:\Python\Python310\lib\site-packages\pptx\package.py", line 6, in <module>
    from pptx.opc.package import OpcPackage
  File "C:\Python\Python310\lib\site-packages\pptx\opc\package.py", line 11, in <module>
    from pptx.compat import is_string, Mapping
  File "C:\Python\Python310\lib\site-packages\pptx\compat\__init__.py", line 14, in <module>
    Container = collections.Container
AttributeError: module 'collections' has no attribute 'Container'
```

**Comment by ssine** [comment]
As mentioned in the https://github.com/ssine/pptx2md#installation section, this package have issues with python version > 3.9
