### ISSUE TITLE
NotImplementedError: Shape instance of unrecognized shape type

### ISSUE THREAD

**Issue by m27315** [ssine/pptx2md#48]
This may be an issue in a package dependency, but I am seeing the following error on an Ubuntu 22.04 box, when converting a given PowerPoint file:

```
$ pptx2md --disable-image --disable-color --disable-escaping \
    --disable-notes -o mypowerpint.pptx.md mypowerpoint.pptx

Traceback (most recent call last):
  File "/home/me/project/venv/lib/python3.11/site-packages/pptx2md/parser.py", line 202, in parse
    shapes = sorted(ungroup_shapes(slide.shapes), key=attrgetter('top', 'left'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/project/venv/lib/python3.11/site-packages/pptx2md/parser.py", line 185, in ungroup_shapes
    if shape.shape_type == MSO_SHAPE_TYPE.GROUP:
       ^^^^^^^^^^^^^^^^
  File "/home/me/project/venv/lib/python3.11/site-packages/pptx/shapes/autoshape.py", line 362, in shape_type
    raise NotImplementedError(msg)
NotImplementedError: Shape instance of unrecognized shape type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/project/venv/bin/pptx2md", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/me/project/venv/lib/python3.11/site-packages/pptx2md/__main__.py", line 141, in main
    parse(prs, out)
  File "/home/me/project/venv/lib/python3.11/site-packages/pptx2md/parser.py", line 207, in parse
    print(sp.shape_type)
          ^^^^^^^^^^^^^
  File "/home/me/project/venv/lib/python3.11/site-packages/pptx/shapes/autoshape.py", line 362, in shape_type
    raise NotImplementedError(msg)
NotImplementedError: Shape instance of unrecognized shape type
```
I am only interested in the text, so I would be thrilled with a solution that simply ignored unknown shapes and kept moving.  :smile: 

Is there additional info I can provide to help troubleshoot?

**Comment by ssine** [comment]
This error should now be ignored and not influence the main process in the new version. try again after `pip install pptx2md==1.6.0`.
