### ISSUE TITLE
ValueError: shape is not a placeholder errors on some PPT's 

### ISSUE THREAD

**Issue by npiper** [ssine/pptx2md#52]
MacOS
Python: 3.9

 is there an 'ignore' option if it can't render ?
 Can it be fixed in the Powerpoint format?
 
 Would it be this one in the library?
 https://github.com/scanny/python-pptx/issues/333
 
 --------
 python3.9/site-packages/pptx/shapes/base.py", line 153, in placeholder_format
    raise ValueError("shape is not a placeholder")
ValueError: shape is not a placeholder

Traceback (most recent call last):
  File "/usr/local/bin/pptx2md", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pptx2md/__main__.py", line 148, in main
    parse(prs, out)
  File "/usr/local/lib/python3.9/site-packages/pptx2md/parser.py", line 237, in parse
    if hasattr(shape, "placeholder_format"):
  File "/usr/local/lib/python3.9/site-packages/pptx/shapes/base.py", line 153, in placeholder_format
    raise ValueError("shape is not a placeholder")
ValueError: shape is not a placeholder

**Comment by ssine** [comment]
should be fixed in version 1.6.1
