### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by npu21** [ssine/pptx2md#6]
After installing pptx2md successfully, came into this error,
```
root@mgt01:~/terraform# pptx2md kubevirt.pptx -o kubevirt.md
Traceback (most recent call last):
  File "/usr/local/bin/pptx2md", line 5, in <module>
    from pptx2md.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/pptx2md/__main__.py", line 78
    print(f'source file {file_path} not exist!')
                                              ^
SyntaxError: invalid syntax
```
even just run cmd pptx2md came into this error too.
Could you take a look?@ssine

**Comment by sleighsoft** [comment]
You may need Python 3 with fstring support.

**Comment by ssine** [comment]
hi @npu21 , @sleighsoft is right, you should have python with version 3.6 or newer installed.
